import type { ThemeConfig } from "antd";
import { neutral, primary, purple, red, blue, orange, green, semantic, yellow, indigo, teal } from "../tokens/colors";
import { typography } from "../tokens/typography";
import { radius } from "../tokens/radius";
import { spacing } from "../tokens";

export const zuiTheme: ThemeConfig = {
  token: {
    colorPrimary: semantic.colorPrimary,
    colorWarning: semantic.colorWarning,
    colorError: semantic.colorError,
    colorInfo: semantic.colorInfo,
    colorSuccess: semantic.colorSuccess,
    colorBgContainer: semantic.colorBgContainer,
    colorBgLayout: semantic.colorBgLayout,
    colorText: semantic.colorText,
    colorTextSecondary: semantic.colorTextSecondary,
    colorTextDisabled: semantic.colorTextDisabled,
    colorBorder: semantic.colorBorder,
    colorBorderSecondary: semantic.colorBorderSecondary,
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSize.sm,
    borderRadius: radius.base,
    borderRadiusLG: radius.md,
    borderRadiusSM: radius.sm,
    blue1: blue[100],
    blue3: blue[300],
    blue5: blue[500],
    blue7: blue[700],
    blue8: blue[800],
    red1: red[100],
    red3: red[300],
    red5: red[500],
    red7: red[700],
    red8: red[800],
    green1: green[100],
    green3: green[300],
    green5: green[500],
    green7: green[700],
    green8: green[800],
    yellow1: yellow[100],
    yellow3: yellow[300],
    yellow5: yellow[500],
    yellow7: yellow[700],
    yellow8: yellow[800],
    orange3: orange[300],
    orange5: orange[500],
    orange7: orange[700],
    purple3: purple[300],
    purple5: purple[500],
    purple7: purple[700],
  },
  components: {
    Button: {
      paddingInlineLG: 60,
      paddingInline: 24,
      paddingInlineSM: 20,
      contentFontSizeLG: typography.fontSize["2xl"],
      contentFontSize: typography.fontSize.md,
      contentLineHeightSM: typography.fontSize.sm,
      defaultHoverBg: neutral["50"],
      defaultActiveColor: neutral["50"],
      defaultActiveBg: semantic.colorPrimary,
      defaultHoverColor: semantic.colorText,
      defaultHoverBorderColor: neutral["400"],
      colorPrimaryHover: primary["700"],
      colorPrimaryActive: primary["400"],
      colorBgContainerDisabled: neutral[300],
      colorTextDisabled: semantic.colorText,
    },
    Alert: {
      colorError: red[300],
      colorErrorBg: red['100'],
      colorErrorBorder: red['300'],
      colorInfo: blue[300],
      colorInfoBg: blue[100],
      colorInfoBorder: blue[300],
      colorSuccess: green[300],
      colorSuccessBg: green[100],
      colorSuccessBorder: green[300],
      colorWarning: orange[300],
      colorWarningBg: yellow[100],
      colorWarningBorder: orange[300],
      borderRadiusLG: 2,
    }
  }
};
